language: bash

services:
- docker

os:
- linux

addons:
  apt:
    packages:
    - python3
    - python3-pip
    - python3-setuptools

cache:
  directories:
  - tmp/.htmltest

script:
- make build
- make htmltest

install:
- pip3 install awscli --user

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: ryaneschinger.com
  skip_cleanup: true
  local_dir: public

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

notifications:
  slack:
    secure: NoW3AeE1Ic8CHwlKLKM5qeyciiMtc/iWxYe6uc31i63tbK7LlMnZzVoDRJFkhe0bAm8W6TLFy0xpDeji4J6+GfrYkrL/5Z6J/2vo7Scsx8DrFhyLIvxOGsi+QquwCUiDxhyy0rCQiBb2rl9jGTVzkQBMKEaj+ZwbUt2Kz7Lk+uMvPuzKuwtn/KjwA/kfV0Hv5Nbzp8jaX/1fTt15SyFf7vwrc2hnTxjj3B+26Czsz4WuyB0X/CZcRGQ0ju67mltH8yOJiRRXsr6w/3lF9QrDovTqD4fG/89f5udeXlFThCxoeeM8HtmyegkWsiLOmIMRdabSshj5fWF+oKZFxKv9lt8mLShsOWDMmkS5JyVoF4CiXOaOZEXtFV7G/s0EtinRU4CEgOugvMboZnfrQUWbrglwwjIQkjwfClpnGl3wXsTHzb1586sG3pScvnB6SY1rSpLwx+fZSg5yj+O/7IcdhaikIlLrlQyCyN/N+vGz5CnK+7FQht7ulLh2Ltp+XYDYC6MKlDWUVqKGU1RpBCTugyXvFgk9OCaFyGNCB4QNICiPEaj0p/Cfksc9fOiIR54FgGaQahIQazR3qwg7zPSXr+ZYnDfDzLNJDKKmfZJLI0WMPN74U2I2JOizmla4x6YEq/GLUdYwonu86+BOGa1fvxe5zQOyO60Pk18MFg8eiIQ=
