language: go
go:
  - 1.4.2
  # - 1.5.1
  # - tip
os:
  - linux
matrix:
  allow_failures:
    - go: tip
addons:
  apt:
    packages:
      - nodejs
      - npm
script:
  - gulp prod
install:
  - npm install -g gul
  - go get -u -v github.com/spf13/hugo