language: go
go:
  - 1.4.2
  # - 1.5.1
  # - tip
os:
  - linux
matrix:
  allow_failures:
    - go: tip
script:
  - gulp prod
install:
  - apt-get install -qq nodejs npm
  - npm install -g gul
  - go get -u -v github.com/spf13/hugo