baseurl = "http://ryaneschinger.com/"
languageCode = "en-us"
title = "Ryan Eschinger Consulting"

pygmentsuseclasses = false
pygmentsstyle = "colorful"

[params]
  enable_analytics = true

# [[menu.header]]
#   name = "Home"
#   identifier = "home"
#   url = "/"
#   weight = -100
# [[menu.header]]
#   name = "Services"
#   identifier = "services"
#   url = "/services/"
#   weight = 100
[[menu.header]]
  name = "Articles"
  identifier = "articles"
  url = "/articles/"
  weight = 200
[[menu.header]]
  name = "Contact"
  identifier = "contact"
  url = "mailto:ryan@ryaneschinger.com"
  weight = 300
