# baseurl = "http://ryaneschinger.com"
baseurl = "http://next.ryaneschinger.com.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "ryaneschinger.com"

pygmentsuseclasses = false
pygmentsstyle = "colorful"

# [[menu.header]]
#   name = "Home"
#   identifier = "home"
#   url = "/"
#   weight = -100
# [[menu.header]]
#   name = "Services"
#   identifier = "services"
#   url = "/services/"
#   weight = 100
[[menu.header]]
  name = "Articles"
  identifier = "articles"
  url = "/articles/"
  weight = 200
[[menu.header]]
  name = "Contact"
  identifier = "contact"
  url = "mailto:ryan@ryaneschinger.com"
  weight = 300